fix: first transition worked out
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sawtooth_poet_tests/test_giskard_network.py", line 59, in test_giskard_network
    'ztest_minimum_win_count': 3,
  File "/usr/lib/python3/dist-packages/sawtooth_poet_tests/test_giskard_network.py", line 126, in _run_giskard_network_test
    TestGiskardUnit.test_global_state_transitions(None, None, giskard_tester.gtrace)
  File "/usr/lib/python3/dist-packages/sawtooth_poet_tests/test_giskard_unit.py", line 556, in test_global_state_transitions
    assert Giskard.protocol_trace(gtrace, False), "A state transition was incorrect"
  File "/usr/lib/python3/dist-packages/sawtooth_poet_engine/giskard.py", line 1455, in protocol_trace
    if not Giskard.GState_transition(tmp_gstate, next_gstate, nodes, old_version):
  File "/usr/lib/python3/dist-packages/sawtooth_poet_engine/giskard.py", line 1410, in GState_transition
    old_version)
  File "/usr/lib/python3/dist-packages/sawtooth_poet_engine/giskard.py", line 1303, in get_inputs_for_transition
    lm = Giskard.propose_block_init_set(state, msg, tmp_block_cache)[1]
  File "/usr/lib/python3/dist-packages/sawtooth_poet_engine/giskard.py", line 730, in propose_block_init_set
    if block_cache.last_proposed_block is None:
AttributeError: 'BlockCacheMock' object has no attribute 'last_proposed_block'